"""add transaction type

Revision ID: cde7fd6e6b88
Revises: bfd39d9a29b0
Create Date: 2026-07-31 14:01:30.948095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde7fd6e6b88'
down_revision: Union[str, Sequence[str], None] = 'bfd39d9a29b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('type', sa.Enum('INCOME', 'EXPENSE', name='transactiontype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'type')
    # ### end Alembic commands ###
